version: "3.8"
services:
  postgres:
    image: postgres:18
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "mipassword-miguel.mendez"
      POSTGRES_DB: "mibasededatos"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./DDL:/docker-entrypoint-initdb.d
volumes:
  pgdata:
